<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="POU" Id="{d42207ec-b17a-4e23-9761-35b90e5767a3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION POU
VAR_INPUT
	a : INT;
	b : INT;
END_VAR
VAR_OUTPUT
	
	c : INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[c := a + b;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>